import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Revision</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Do a question now:
        </h1>

        <div className={styles.grid}>
          <a href="/questions/Mathematics" className={styles.card}>
            <h2>Mathematics</h2>
            <p>Pure 1~4, S1 and M1</p>
          </a>

          <a href="/questions/Economics" className={styles.card}>
            <h2>Economics</h2>
            <p>Unit 1~4</p>
          </a>

          <a
            href="/questions/Biology"
            className={styles.card}
          >
            <h2>Biology</h2>
            <p>Unit 1~6</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/sidharthmirch"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️ by Sid
        </a>
      </footer>
    </div>
  );
}
