import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Revision</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Do a question now:</h1>

        <div className={styles.grid}>
          <Link href="/questions/Mathematics" className={styles.card}>
            <h2 className={styles.card}>Mathematics</h2>
          </Link>

          <Link href="/questions/Economics" className={styles.card}>
            <h2 className={styles.card}>Economics</h2>
          </Link>

          <Link href="/questions/Biology">
            <h2 className={styles.card}>Biology</h2>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://github.com/sidharthmirch"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️ by Sid
        </Link>
      </footer>
    </div>
  );
}
